name: english
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_tts: ^4.0.2

  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.0.3

  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  get_it: ^7.7.0
  connectivity_plus: ^6.0.3
  equatable: ^2.0.5

  easy_localization: ^3.0.7
  zoom_tap_animation: ^1.1.0
  shimmer: ^3.0.0
  curved_navigation_bar: ^1.0.6
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/translation/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
