// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLB9ZTZscRYJU5CYj_NpeRazUdKY00KA4',
    appId: '1:710949537045:web:aa22ec5ef0c6508827951c',
    messagingSenderId: '710949537045',
    projectId: 'language-e7f9e',
    authDomain: 'language-e7f9e.firebaseapp.com',
    storageBucket: 'language-e7f9e.appspot.com',
    measurementId: 'G-1JCK0TSBN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKWL0xXU_ROjcv_XMdWCohZRbARkgkBU',
    appId: '1:710949537045:android:9bc1a314a9099bad27951c',
    messagingSenderId: '710949537045',
    projectId: 'language-e7f9e',
    storageBucket: 'language-e7f9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvnvZ0gPqTTYSAkZM7pT2BCS2qjfeWPS4',
    appId: '1:710949537045:ios:a811df6c64cbb91427951c',
    messagingSenderId: '710949537045',
    projectId: 'language-e7f9e',
    storageBucket: 'language-e7f9e.appspot.com',
    iosBundleId: 'com.example.english',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvnvZ0gPqTTYSAkZM7pT2BCS2qjfeWPS4',
    appId: '1:710949537045:ios:a811df6c64cbb91427951c',
    messagingSenderId: '710949537045',
    projectId: 'language-e7f9e',
    storageBucket: 'language-e7f9e.appspot.com',
    iosBundleId: 'com.example.english',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLB9ZTZscRYJU5CYj_NpeRazUdKY00KA4',
    appId: '1:710949537045:web:5f95f2d107fc7fab27951c',
    messagingSenderId: '710949537045',
    projectId: 'language-e7f9e',
    authDomain: 'language-e7f9e.firebaseapp.com',
    storageBucket: 'language-e7f9e.appspot.com',
    measurementId: 'G-DJLX2HH30B',
  );
}
